"""add aml_types to aml_cases

Revision ID: 033ceaf844a8
Revises: e3786b3bed0f
Create Date: 2026-03-28 20:56:17.928954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033ceaf844a8'
down_revision: Union[str, None] = 'e3786b3bed0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aml_cases', sa.Column('aml_types', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aml_cases', 'aml_types')
    # ### end Alembic commands ###
