"""add risk_score_breakdown and last_rescreen_at to aml_customers

Revision ID: 0e9a8e50703a
Revises: f65af2533a0e
Create Date: 2026-04-21 14:51:42.752069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9a8e50703a'
down_revision: Union[str, None] = 'f65af2533a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aml_customers', sa.Column('risk_score_breakdown', sa.JSON(), nullable=True))
    op.add_column('aml_customers', sa.Column('last_rescreen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aml_customers', 'last_rescreen_at')
    op.drop_column('aml_customers', 'risk_score_breakdown')
    # ### end Alembic commands ###
