"""empty message

Revision ID: 12a4d5b05a23
Revises: 5e4a89919531
Create Date: 2026-01-17 14:17:30.438884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a4d5b05a23'
down_revision: Union[str, None] = '5e4a89919531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_pobo', sa.Column('beneficiary_country', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_pobo', 'beneficiary_country')
    # ### end Alembic commands ###
