"""add cascade delete to clients user_id fkey

Revision ID: 22f31128fd28
Revises: 605596c5fa3c
Create Date: 2026-03-29 13:58:00.450898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f31128fd28'
down_revision: Union[str, None] = '605596c5fa3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_user_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_user_id_fkey'), 'clients', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
