"""empty message

Revision ID: 23d3fb3360b0
Revises: 46e30a4164bb
Create Date: 2026-01-21 16:34:03.801099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d3fb3360b0'
down_revision: Union[str, None] = '46e30a4164bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_pobo_terms_executing_bank_fkey'), 'order_pobo_terms', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('order_pobo_terms_executing_bank_fkey'), 'order_pobo_terms', 'payeer_accounts', ['executing_bank'], ['account_no'])
    # ### end Alembic commands ###
