"""empty message

Revision ID: 2b85f9b33f02
Revises: e9318028690a
Create Date: 2025-12-24 08:46:00.190597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b85f9b33f02'
down_revision: Union[str, None] = 'e9318028690a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_alias_1', sa.String(length=255), nullable=True),
    sa.Column('client_alias_2', sa.String(length=255), nullable=True),
    sa.Column('client_alias_3', sa.String(length=255), nullable=True),
    sa.Column('client_reg_number', sa.String(length=255), nullable=True),
    sa.Column('client_tax_number', sa.String(length=255), nullable=True),
    sa.Column('client_reg_country', sa.String(length=255), nullable=True),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('status_sign', sa.String(length=255), nullable=True),
    sa.Column('date_signing', sa.Date(), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('client_director', sa.String(length=255), nullable=True),
    sa.Column('client_mail', sa.String(length=255), nullable=True),
    sa.Column('last_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_foreign_key(None, 'mandiri_statement', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key(None, 'order_cobo_terms', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key(None, 'order_pobo_terms', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key(None, 'orders_cobo', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key(None, 'orders_pobo', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key(None, 'other_bank_statements', 'clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'other_bank_statements', type_='foreignkey')
    op.drop_constraint(None, 'orders_pobo', type_='foreignkey')
    op.drop_constraint(None, 'orders_cobo', type_='foreignkey')
    op.drop_constraint(None, 'order_pobo_terms', type_='foreignkey')
    op.drop_constraint(None, 'order_cobo_terms', type_='foreignkey')
    op.drop_constraint(None, 'mandiri_statement', type_='foreignkey')
    op.drop_table('clients')
    op.drop_table('users')
    # ### end Alembic commands ###
