"""empty message

Revision ID: 2d8941b9c331
Revises: 12a4d5b05a23
Create Date: 2026-01-18 18:30:55.018603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8941b9c331'
down_revision: Union[str, None] = '12a4d5b05a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_pobo_terms', sa.Column('GAN_bank_name', sa.String(length=255), nullable=True))
    op.add_column('order_pobo_terms', sa.Column('GAN_bank_account', sa.String(length=255), nullable=True))
    op.add_column('order_pobo_terms', sa.Column('date_report', sa.Date(), nullable=True))
    op.add_column('order_pobo_terms', sa.Column('conversion_method', sa.String(length=255), nullable=True))
    op.add_column('order_pobo_terms', sa.Column('base_currency', sa.String(length=10), nullable=True))
    op.add_column('order_pobo_terms', sa.Column('FX', sa.Boolean(), nullable=True))
    op.add_column('order_pobo_terms', sa.Column('executing_bank', sa.String(length=255), nullable=True))
    op.add_column('order_pobo_terms', sa.Column('FX_executing_bank', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('order_pobo_terms', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'order_pobo_terms', 'payeer_accounts', ['executing_bank'], ['account_no'])
    op.create_foreign_key(None, 'order_pobo_terms', 'currencies', ['base_currency'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_pobo_terms', type_='foreignkey')
    op.drop_constraint(None, 'order_pobo_terms', type_='foreignkey')
    op.drop_column('order_pobo_terms', 'status')
    op.drop_column('order_pobo_terms', 'FX_executing_bank')
    op.drop_column('order_pobo_terms', 'executing_bank')
    op.drop_column('order_pobo_terms', 'FX')
    op.drop_column('order_pobo_terms', 'base_currency')
    op.drop_column('order_pobo_terms', 'conversion_method')
    op.drop_column('order_pobo_terms', 'date_report')
    op.drop_column('order_pobo_terms', 'GAN_bank_account')
    op.drop_column('order_pobo_terms', 'GAN_bank_name')
    # ### end Alembic commands ###
