"""empty message

Revision ID: 301ce7e2662c
Revises: 2b85f9b33f02
Create Date: 2026-01-08 09:21:09.083512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301ce7e2662c'
down_revision: Union[str, None] = '2b85f9b33f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_kyc_profiles',
    sa.Column('profile_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index('idx_kyc_profile_client', 'onboarding_kyc_profiles', ['client_id'], unique=False)
    op.create_index('idx_kyc_profile_status', 'onboarding_kyc_profiles', ['status'], unique=False)
    op.create_table('onboarding_kyc_documents',
    sa.Column('doc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['onboarding_kyc_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('idx_kyc_doc_profile', 'onboarding_kyc_documents', ['profile_id'], unique=False)
    op.create_index('idx_kyc_doc_type', 'onboarding_kyc_documents', ['doc_type'], unique=False)
    op.create_table('onboarding_kyc_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['onboarding_kyc_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kyc_history_date', 'onboarding_kyc_status_history', ['changed_at'], unique=False)
    op.create_index('idx_kyc_history_profile', 'onboarding_kyc_status_history', ['profile_id'], unique=False)
    op.create_table('onboarding_kyc_ubos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('ubo_name', sa.String(length=255), nullable=True),
    sa.Column('shareholding_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('residence_country', sa.CHAR(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['onboarding_kyc_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kyc_ubo_profile', 'onboarding_kyc_ubos', ['profile_id'], unique=False)
    op.add_column('clients', sa.Column('kyc_status', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('kyc_submitted_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('kyc_decided_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('kyc_decided_by', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['kyc_decided_by'], ['user_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'kyc_decided_by')
    op.drop_column('clients', 'kyc_decided_at')
    op.drop_column('clients', 'kyc_submitted_at')
    op.drop_column('clients', 'kyc_status')
    op.drop_index('idx_kyc_ubo_profile', table_name='onboarding_kyc_ubos')
    op.drop_table('onboarding_kyc_ubos')
    op.drop_index('idx_kyc_history_profile', table_name='onboarding_kyc_status_history')
    op.drop_index('idx_kyc_history_date', table_name='onboarding_kyc_status_history')
    op.drop_table('onboarding_kyc_status_history')
    op.drop_index('idx_kyc_doc_type', table_name='onboarding_kyc_documents')
    op.drop_index('idx_kyc_doc_profile', table_name='onboarding_kyc_documents')
    op.drop_table('onboarding_kyc_documents')
    op.drop_index('idx_kyc_profile_status', table_name='onboarding_kyc_profiles')
    op.drop_index('idx_kyc_profile_client', table_name='onboarding_kyc_profiles')
    op.drop_table('onboarding_kyc_profiles')
    # ### end Alembic commands ###
