"""add alias to payeer_accounts

Revision ID: 34ed5d9c6ded
Revises: eb922fbb5c78
Create Date: 2026-03-26 09:28:49.864239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ed5d9c6ded'
down_revision: Union[str, None] = 'eb922fbb5c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payeer_accounts', sa.Column('alias', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payeer_accounts', 'alias')
    # ### end Alembic commands ###
