"""empty message

Revision ID: 3a94f1a4afb6
Revises: 23d3fb3360b0
Create Date: 2026-01-29 09:20:29.709287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a94f1a4afb6'
down_revision: Union[str, None] = '23d3fb3360b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executed_orders', sa.Column('mt103_no', sa.String(length=255), nullable=True))
    op.add_column('executed_orders', sa.Column('mt103_date', sa.Date(), nullable=True))
    op.add_column('executed_orders', sa.Column('transaction_status_no', sa.String(length=255), nullable=True))
    op.add_column('executed_orders', sa.Column('transaction_status_date', sa.Date(), nullable=True))
    op.add_column('executed_orders', sa.Column('transaction_status_status', sa.String(length=50), nullable=True))
    op.add_column('executed_orders', sa.Column('act_report_no', sa.String(length=255), nullable=True))
    op.add_column('executed_orders', sa.Column('act_report_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executed_orders', 'act_report_date')
    op.drop_column('executed_orders', 'act_report_no')
    op.drop_column('executed_orders', 'transaction_status_status')
    op.drop_column('executed_orders', 'transaction_status_date')
    op.drop_column('executed_orders', 'transaction_status_no')
    op.drop_column('executed_orders', 'mt103_date')
    op.drop_column('executed_orders', 'mt103_no')
    # ### end Alembic commands ###
