"""empty message

Revision ID: 449d52f1b336
Revises: 9829c320ab1d
Create Date: 2026-01-08 09:54:31.034465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449d52f1b336'
down_revision: Union[str, None] = '9829c320ab1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nda_group_companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=True),
    sa.Column('company_name_ru', sa.String(length=255), nullable=True),
    sa.Column('company_name_en', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=50), nullable=True),
    sa.Column('address_ru', sa.Text(), nullable=True),
    sa.Column('address_en', sa.Text(), nullable=True),
    sa.Column('signatory_ru', sa.String(length=500), nullable=True),
    sa.Column('signatory_en', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code')
    )
    op.create_table('nda_requests',
    sa.Column('nda_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('template_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('term_ru', sa.String(length=100), nullable=True),
    sa.Column('term_en', sa.String(length=100), nullable=True),
    sa.Column('group_company_id', sa.BigInteger(), nullable=True),
    sa.Column('partner_inn', sa.String(length=50), nullable=True),
    sa.Column('partner_name_ru', sa.String(length=500), nullable=True),
    sa.Column('partner_address_ru', sa.Text(), nullable=True),
    sa.Column('partner_name_en', sa.String(length=500), nullable=True),
    sa.Column('partner_address_en', sa.Text(), nullable=True),
    sa.Column('partner_signatory_ru', sa.String(length=500), nullable=True),
    sa.Column('partner_signatory_en', sa.String(length=500), nullable=True),
    sa.Column('partner_contact_name', sa.String(length=255), nullable=True),
    sa.Column('partner_contact_email', sa.String(length=255), nullable=True),
    sa.Column('partner_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('paper_copy_required', sa.Boolean(), nullable=False),
    sa.Column('generated_file_key', sa.String(length=500), nullable=True),
    sa.Column('generated_file_url', sa.Text(), nullable=True),
    sa.Column('generated_file_name', sa.String(length=255), nullable=True),
    sa.Column('generated_file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['group_company_id'], ['nda_group_companies.id'], ),
    sa.PrimaryKeyConstraint('nda_id')
    )
    op.create_index('idx_nda_request_client', 'nda_requests', ['client_id'], unique=False)
    op.create_index('idx_nda_request_status', 'nda_requests', ['status'], unique=False)
    op.create_table('nda_documents',
    sa.Column('doc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nda_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nda_id'], ['nda_requests.nda_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('idx_nda_doc_nda', 'nda_documents', ['nda_id'], unique=False)
    op.create_index('idx_nda_doc_type', 'nda_documents', ['doc_type'], unique=False)
    op.create_table('nda_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nda_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['nda_id'], ['nda_requests.nda_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nda_history_date', 'nda_status_history', ['changed_at'], unique=False)
    op.create_index('idx_nda_history_nda', 'nda_status_history', ['nda_id'], unique=False)
    op.add_column('clients', sa.Column('nda_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'nda_status')
    op.drop_index('idx_nda_history_nda', table_name='nda_status_history')
    op.drop_index('idx_nda_history_date', table_name='nda_status_history')
    op.drop_table('nda_status_history')
    op.drop_index('idx_nda_doc_type', table_name='nda_documents')
    op.drop_index('idx_nda_doc_nda', table_name='nda_documents')
    op.drop_table('nda_documents')
    op.drop_index('idx_nda_request_status', table_name='nda_requests')
    op.drop_index('idx_nda_request_client', table_name='nda_requests')
    op.drop_table('nda_requests')
    op.drop_table('nda_group_companies')
    # ### end Alembic commands ###
