"""empty message

Revision ID: 5e4a89919531
Revises: c5c415abf577
Create Date: 2026-01-15 07:10:50.752875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4a89919531'
down_revision: Union[str, None] = 'c5c415abf577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку с server_default для существующих записей
    op.add_column('clients', sa.Column('orders_count', sa.BigInteger(), nullable=True, server_default='0'))
    # Обновляем существующие записи
    op.execute("UPDATE clients SET orders_count = 0 WHERE orders_count IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'orders_count')
    # ### end Alembic commands ###
