"""add terms_accepted to users

Revision ID: 605596c5fa3c
Revises: 033ceaf844a8
Create Date: 2026-03-29 13:10:39.489767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605596c5fa3c'
down_revision: Union[str, None] = '033ceaf844a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'terms_accepted')
    # ### end Alembic commands ###
