"""empty message

Revision ID: 67b7f943ae97
Revises: 0689c0c00d28
Create Date: 2026-02-04 11:24:13.297213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b7f943ae97'
down_revision: Union[str, None] = '0689c0c00d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('products_interested', sa.JSON(), nullable=True),
    sa.Column('monthly_volume', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_agreed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_created', 'leads', ['created_at'], unique=False)
    op.create_index('idx_lead_email', 'leads', ['business_email'], unique=False)
    op.create_index('idx_lead_status', 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lead_status', table_name='leads')
    op.drop_index('idx_lead_email', table_name='leads')
    op.drop_index('idx_lead_created', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
