"""add bank_manual_override to orders_pobo

Revision ID: 6c27839a655f
Revises: 8eae91d31554
Create Date: 2026-05-07 18:30:22.499458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c27839a655f'
down_revision: Union[str, None] = '8eae91d31554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_pobo', sa.Column('bank_manual_override', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_pobo', 'bank_manual_override')
    # ### end Alembic commands ###
