"""widen_entries_address_to_4096

Revision ID: 7bd9a702cb29
Revises: f73916971801
Create Date: 2026-03-14 19:21:55.296360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd9a702cb29'
down_revision: Union[str, None] = 'f73916971801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'address',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=4096),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'address',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
