"""empty message

Revision ID: 84b42a77c2c4
Revises: 3a94f1a4afb6
Create Date: 2026-01-30 15:31:55.236301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b42a77c2c4'
down_revision: Union[str, None] = '3a94f1a4afb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_pobo_terms', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_pobo_terms', 'description')
    # ### end Alembic commands ###
