"""add_aml_tables

Revision ID: 886b81748195
Revises: 7bd9a702cb29
Create Date: 2026-03-19 12:18:56.375814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886b81748195'
down_revision: Union[str, None] = '7bd9a702cb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aml_customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_identifier', sa.String(length=255), nullable=True),
    sa.Column('external_identifier', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('screening_result', sa.String(length=100), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_identifier')
    )
    op.create_index('idx_aml_customer_external', 'aml_customers', ['external_identifier'], unique=False)
    op.create_index('idx_aml_customer_identifier', 'aml_customers', ['customer_identifier'], unique=False)
    op.create_index('idx_aml_customer_monitored', 'aml_customers', ['monitored'], unique=False)
    op.create_index('idx_aml_customer_risk', 'aml_customers', ['risk_level'], unique=False)
    op.create_table('aml_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aml_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('external_alert_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('match_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aml_customer_id'], ['aml_customers.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aml_alert_customer', 'aml_alerts', ['aml_customer_id'], unique=False)
    op.create_index('idx_aml_alert_status', 'aml_alerts', ['status'], unique=False)
    op.create_table('aml_cases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aml_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('external_case_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aml_customer_id'], ['aml_customers.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aml_case_customer', 'aml_cases', ['aml_customer_id'], unique=False)
    op.create_index('idx_aml_case_status', 'aml_cases', ['status'], unique=False)
    op.create_table('aml_risk_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aml_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('old_risk_level', sa.String(length=50), nullable=False),
    sa.Column('new_risk_level', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aml_customer_id'], ['aml_customers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aml_risk_override_customer', 'aml_risk_overrides', ['aml_customer_id'], unique=False)
    op.create_table('aml_screenings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aml_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('screening_type', sa.String(length=50), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aml_customer_id'], ['aml_customers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aml_screening_customer', 'aml_screenings', ['aml_customer_id'], unique=False)
    op.create_table('aml_case_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aml_case_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aml_case_id'], ['aml_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aml_comment_case', 'aml_case_comments', ['aml_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_aml_comment_case', table_name='aml_case_comments')
    op.drop_table('aml_case_comments')
    op.drop_index('idx_aml_screening_customer', table_name='aml_screenings')
    op.drop_table('aml_screenings')
    op.drop_index('idx_aml_risk_override_customer', table_name='aml_risk_overrides')
    op.drop_table('aml_risk_overrides')
    op.drop_index('idx_aml_case_status', table_name='aml_cases')
    op.drop_index('idx_aml_case_customer', table_name='aml_cases')
    op.drop_table('aml_cases')
    op.drop_index('idx_aml_alert_status', table_name='aml_alerts')
    op.drop_index('idx_aml_alert_customer', table_name='aml_alerts')
    op.drop_table('aml_alerts')
    op.drop_index('idx_aml_customer_risk', table_name='aml_customers')
    op.drop_index('idx_aml_customer_monitored', table_name='aml_customers')
    op.drop_index('idx_aml_customer_identifier', table_name='aml_customers')
    op.drop_index('idx_aml_customer_external', table_name='aml_customers')
    op.drop_table('aml_customers')
    # ### end Alembic commands ###
