"""add kyc_override to client

Revision ID: 8eae91d31554
Revises: e3d6977341de
Create Date: 2026-05-07 16:44:13.989058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eae91d31554'
down_revision: Union[str, None] = 'e3d6977341de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('kyc_override', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'kyc_override')
    # ### end Alembic commands ###
