"""add indexes for orders and clients tables

Revision ID: ac190bf52f81
Revises: add_report_export_fields
Create Date: 2026-03-07 19:30:23.750058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac190bf52f81'
down_revision: Union[str, None] = 'add_report_export_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_client_user', 'clients', ['user_id'], unique=False)
    op.create_index('idx_executed_source_order', 'executed_orders', ['source_order_id'], unique=False)
    op.create_index('idx_order_pobo_term_order', 'order_pobo_terms', ['order_id'], unique=False)
    op.create_index('idx_order_pobo_client', 'orders_pobo', ['client_id'], unique=False)
    op.create_index('idx_order_pobo_deleted', 'orders_pobo', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_pobo_deleted', table_name='orders_pobo')
    op.drop_index('idx_order_pobo_client', table_name='orders_pobo')
    op.drop_index('idx_order_pobo_term_order', table_name='order_pobo_terms')
    op.drop_index('idx_executed_source_order', table_name='executed_orders')
    op.drop_index('idx_client_user', table_name='clients')
    # ### end Alembic commands ###
