"""empty message

Revision ID: c5c415abf577
Revises: 449d52f1b336
Create Date: 2026-01-12 21:55:49.992707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c415abf577'
down_revision: Union[str, None] = '449d52f1b336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('payeer_accounts', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('payeer_accounts', sa.Column('bank_address', sa.Text(), nullable=True))
    op.add_column('payeer_accounts', sa.Column('bank_corr_account', sa.String(length=255), nullable=True))
    op.add_column('payeer_accounts', sa.Column('bank_bic', sa.String(length=255), nullable=True))
    op.add_column('payeer_accounts', sa.Column('bank_country', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payeer_accounts', 'bank_country')
    op.drop_column('payeer_accounts', 'bank_bic')
    op.drop_column('payeer_accounts', 'bank_corr_account')
    op.drop_column('payeer_accounts', 'bank_address')
    op.drop_column('payeer_accounts', 'bank_name')
    op.drop_column('clients', 'description')
    # ### end Alembic commands ###
