"""test

Revision ID: ce48c543699a
Revises: f52398d45376
Create Date: 2026-02-03 19:03:16.322647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce48c543699a'
down_revision: Union[str, None] = 'f52398d45376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_request_badges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('badge_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('staff_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_badge_active', 'client_request_badges', ['is_active'], unique=False)
    op.create_index('idx_badge_client', 'client_request_badges', ['client_id'], unique=False)
    op.create_index('idx_badge_client_type', 'client_request_badges', ['client_id', 'badge_type'], unique=True)
    op.add_column('clients', sa.Column('account_status', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('account_hold_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'account_hold_reason')
    op.drop_column('clients', 'account_status')
    op.drop_index('idx_badge_client_type', table_name='client_request_badges')
    op.drop_index('idx_badge_client', table_name='client_request_badges')
    op.drop_index('idx_badge_active', table_name='client_request_badges')
    op.drop_table('client_request_badges')
    # ### end Alembic commands ###
