"""init

Revision ID: dd5aafb36ce2
Revises: 
Create Date: 2025-12-22 17:00:02.211248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5aafb36ce2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_reconcile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance_openning', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_fv_opening', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_remuneration_opening', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_fv', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_remuneration', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('debit_cobo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_overlapped_cobo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('debit_remuneration', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('debit_other_costs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exchange_rate_differences', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deposit_movement_fv', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deposit_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_closing', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_fv_closing', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_remuneration_closing', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ss_profit_fixed_rub', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('bic_directory',
    sa.Column('bic', sa.String(length=11), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_address', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('bic')
    )
    op.create_table('content_blocks',
    sa.Column('block_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('block_key', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('counterparties',
    sa.Column('counterparty_id', sa.String(length=255), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_alias_1', sa.String(length=255), nullable=True),
    sa.Column('counterparty_alias_2', sa.String(length=255), nullable=True),
    sa.Column('counterparty_alias_3', sa.String(length=255), nullable=True),
    sa.Column('counterparty_reg_number', sa.String(length=255), nullable=True),
    sa.Column('counterparty_reg_country', sa.String(length=255), nullable=True),
    sa.Column('last_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('counterparty_id')
    )
    op.create_table('countries',
    sa.Column('ctry_cd', sa.CHAR(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('ctry_cd'),
    sa.UniqueConstraint('country_name')
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_list', sa.String(length=255), nullable=True),
    sa.Column('entry_type', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('name1', sa.String(length=255), nullable=True),
    sa.Column('name2', sa.String(length=255), nullable=True),
    sa.Column('name3', sa.String(length=255), nullable=True),
    sa.Column('name4', sa.String(length=255), nullable=True),
    sa.Column('tittle', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=2048), nullable=True),
    sa.Column('dob', sa.String(length=255), nullable=True),
    sa.Column('pob', sa.String(length=255), nullable=True),
    sa.Column('alias', sa.String(length=1024), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('passport_no', sa.String(length=255), nullable=True),
    sa.Column('identity_no', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=1024), nullable=True),
    sa.Column('additional_info', sa.String(length=4096), nullable=True),
    sa.Column('load_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('usd_rub', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('eur_rub', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('cny_rub', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('usd', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('eur', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('cny', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('faq_items',
    sa.Column('faq_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_table('instruction_exports',
    sa.Column('export_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('export_params', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_table('kyc_companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('alias_1', sa.String(length=255), nullable=True),
    sa.Column('alias_2', sa.String(length=255), nullable=True),
    sa.Column('alias_3', sa.String(length=255), nullable=True),
    sa.Column('alias_4', sa.String(length=255), nullable=True),
    sa.Column('alias_5', sa.String(length=255), nullable=True),
    sa.Column('address_1', sa.String(length=255), nullable=True),
    sa.Column('address_2', sa.String(length=255), nullable=True),
    sa.Column('address_3', sa.String(length=255), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('type_of_list', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_individuals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('alias_1', sa.String(length=255), nullable=True),
    sa.Column('alias_2', sa.String(length=255), nullable=True),
    sa.Column('alias_3', sa.String(length=255), nullable=True),
    sa.Column('alias_4', sa.String(length=255), nullable=True),
    sa.Column('alias_5', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('passport_number', sa.String(length=255), nullable=True),
    sa.Column('identity_number', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.String(length=255), nullable=True),
    sa.Column('place_of_birth', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('type_of_list', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_search_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('searched_by', sa.String(length=255), nullable=True),
    sa.Column('search_type', sa.String(length=50), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('match_mode', sa.String(length=50), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=70), nullable=False),
    sa.Column('beneficiary_address', sa.String(length=105), nullable=False),
    sa.Column('destination_account', sa.String(length=35), nullable=False),
    sa.Column('country_bank', sa.String(length=2), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_address', sa.String(length=255), nullable=True),
    sa.Column('transaction_remark', sa.String(length=500), nullable=True),
    sa.Column('remark_mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_payment_order_bic', 'payment_order', ['bic'], unique=False)
    op.create_index('idx_payment_order_client', 'payment_order', ['client_id'], unique=False)
    op.create_index('idx_payment_order_status', 'payment_order', ['status'], unique=False)
    op.create_table('sales_leads',
    sa.Column('lead_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_alias_1', sa.String(length=255), nullable=True),
    sa.Column('client_alias_2', sa.String(length=255), nullable=True),
    sa.Column('client_alias_3', sa.String(length=255), nullable=True),
    sa.Column('client_reg_number', sa.String(length=255), nullable=True),
    sa.Column('client_tax_number', sa.String(length=255), nullable=True),
    sa.Column('client_reg_country', sa.String(length=255), nullable=True),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('status_sign', sa.String(length=255), nullable=True),
    sa.Column('date_signing', sa.Date(), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('client_director', sa.String(length=255), nullable=True),
    sa.Column('client_mail', sa.String(length=255), nullable=True),
    sa.Column('last_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('membercheck_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('search_history_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_scan_id', sa.String(length=255), nullable=True),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('report_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_history_id'], ['kyc_search_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_directory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('bic_swift_cd', sa.String(length=11), nullable=True),
    sa.Column('chips_uid', sa.String(length=20), nullable=True),
    sa.Column('nm', sa.String(length=255), nullable=True),
    sa.Column('org_national_cd', sa.String(length=50), nullable=True),
    sa.Column('branch_nm', sa.String(length=255), nullable=True),
    sa.Column('addr_1', sa.String(length=255), nullable=True),
    sa.Column('addr_2', sa.String(length=255), nullable=True),
    sa.Column('addr_3', sa.String(length=255), nullable=True),
    sa.Column('city_nm', sa.String(length=120), nullable=True),
    sa.Column('substate_nm', sa.String(length=120), nullable=True),
    sa.Column('state_nm', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('is_inactive', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ctry_cd', sa.CHAR(length=2), nullable=True),
    sa.Column('national_org_dir_cd', sa.String(length=50), nullable=True),
    sa.Column('inter_bank_connection_sts', sa.String(length=50), nullable=True),
    sa.Column('is_active_mars', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ctry_cd'], ['countries.ctry_cd'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orgdir_bic', 'org_directory', ['bic_swift_cd'], unique=False)
    op.create_index('idx_orgdir_country', 'org_directory', ['ctry_cd'], unique=False)
    op.create_table('payeer_accounts',
    sa.Column('account_no', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('account_no')
    )
    op.create_table('refunds',
    sa.Column('refund_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status_received', sa.String(length=50), nullable=True),
    sa.Column('type_refund', sa.String(length=50), nullable=True),
    sa.Column('cur_refund', sa.String(length=10), nullable=True),
    sa.Column('rate_refund', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('amount_refund', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remuneration_refund', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_refund_base_cur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('refund_id')
    )
    op.create_table('thresholds',
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_threshold', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('currency')
    )
    op.create_table('mandiri_fx_fifo',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('account_no', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('transaction_code', sa.String(length=255), nullable=True),
    sa.Column('transaction_code_desc', sa.String(length=255), nullable=True),
    sa.Column('description_main', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('description_extra', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('order_id_auto', sa.String(length=255), nullable=True),
    sa.Column('order_id_manual', sa.String(length=255), nullable=True),
    sa.Column('manual_desc', sa.Text(), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('auto_desc', sa.Text(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('is_inhouse', sa.Boolean(), nullable=True),
    sa.Column('forex_flag', sa.Boolean(), nullable=True),
    sa.Column('open_fx_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fx_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_used_from_fx', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fx_used_from_direct', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('open_direct_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('direct_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fx_lots_used', sa.Text(), nullable=True),
    sa.Column('fx_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_no'], ['payeer_accounts.account_no'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandiri_statement',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('account_no', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('transaction_code', sa.String(length=255), nullable=True),
    sa.Column('transaction_code_desc', sa.String(length=255), nullable=True),
    sa.Column('description_main', sa.Text(), nullable=True),
    sa.Column('description_extra', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('order_id_auto', sa.String(length=255), nullable=True),
    sa.Column('order_id_manual', sa.String(length=255), nullable=True),
    sa.Column('description_auto', sa.Text(), nullable=True),
    sa.Column('description_manual', sa.Text(), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('counterparty_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_no'], ['payeer_accounts.account_no'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.counterparty_id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_cobo',
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('document_order_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('date_fixing', sa.Date(), nullable=True),
    sa.Column('date_paid', sa.Date(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('counterparty_id', sa.String(length=255), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_status', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.counterparty_id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('orders_pobo',
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('counterparty_id', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_adress', sa.Text(), nullable=True),
    sa.Column('destination_account', sa.String(length=255), nullable=True),
    sa.Column('bank_country', sa.String(length=255), nullable=True),
    sa.Column('bank_bic', sa.String(length=11), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_address', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('invocie_required', sa.Boolean(), nullable=True),
    sa.Column('invocie_received', sa.Boolean(), nullable=True),
    sa.Column('payment_proof', sa.Boolean(), nullable=True),
    sa.Column('non_mandiri_execution', sa.Boolean(), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_status', sa.DateTime(), nullable=True),
    sa.Column('include', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.counterparty_id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('other_bank_statements',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('account_no', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('transaction_remark', sa.Text(), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('order_retrived_date', sa.Date(), nullable=True),
    sa.Column('order_retrived_id', sa.String(length=255), nullable=True),
    sa.Column('order_id_auto', sa.String(length=255), nullable=True),
    sa.Column('order_id_manual', sa.String(length=255), nullable=True),
    sa.Column('description_auto', sa.Text(), nullable=True),
    sa.Column('description_manual', sa.Text(), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executed_orders',
    sa.Column('executed_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_order_id', sa.String(length=255), nullable=True),
    sa.Column('doc_package_status', sa.String(length=50), nullable=True),
    sa.Column('mt103_status', sa.String(length=50), nullable=True),
    sa.Column('settled_status', sa.String(length=10), nullable=True),
    sa.Column('refund_flag', sa.String(length=10), nullable=True),
    sa.Column('staff_description', sa.Text(), nullable=True),
    sa.Column('mt103_file_url', sa.Text(), nullable=True),
    sa.Column('transaction_status_file_url', sa.Text(), nullable=True),
    sa.Column('act_report_file_url', sa.Text(), nullable=True),
    sa.Column('moved_at', sa.DateTime(), nullable=True),
    sa.Column('moved_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['source_order_id'], ['orders_pobo.order_id'], ),
    sa.PrimaryKeyConstraint('executed_id')
    )
    op.create_table('instruction_export_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['instruction_exports.export_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders_pobo.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandiri_order_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mandiri_statement_id', sa.String(length=255), nullable=True),
    sa.Column('order_id_manual', sa.String(length=255), nullable=True),
    sa.Column('description_manual', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mandiri_statement_id'], ['mandiri_statement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_cobo_terms',
    sa.Column('term_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('client_payout_currency', sa.String(length=10), nullable=True),
    sa.Column('data_paid', sa.Date(), nullable=True),
    sa.Column('data_fixing', sa.Date(), nullable=True),
    sa.Column('remuneration', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_remuneration', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_to_be_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exchange_rate_manual', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('bank_statement_in_type', sa.String(length=50), nullable=True),
    sa.Column('bank_statement_in_id', sa.String(length=255), nullable=True),
    sa.Column('bank_statement_out_type', sa.String(length=50), nullable=True),
    sa.Column('bank_statement_out_id', sa.String(length=255), nullable=True),
    sa.Column('amount_to_be_paid_target_cur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_paid_target_cur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders_cobo.order_id'], ),
    sa.PrimaryKeyConstraint('term_id')
    )
    op.create_table('order_documents',
    sa.Column('doc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders_pobo.order_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('idx_order_docs_type', 'order_documents', ['order_id', 'doc_type'], unique=False)
    op.create_table('order_pobo_terms',
    sa.Column('term_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('client_payment_currency', sa.String(length=10), nullable=True),
    sa.Column('date_paid', sa.Date(), nullable=True),
    sa.Column('data_fixing', sa.Date(), nullable=True),
    sa.Column('remuneration_type', sa.String(length=50), nullable=True),
    sa.Column('remuneration_percentage', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('remuneration_fixed', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_remuneration', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_to_be_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exchange_rate_manual', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('bank_statement_in_type', sa.String(length=50), nullable=True),
    sa.Column('bank_statement_in_id', sa.String(length=255), nullable=True),
    sa.Column('bank_statement_out_type', sa.String(length=50), nullable=True),
    sa.Column('bank_statement_out_id', sa.String(length=255), nullable=True),
    sa.Column('amount_to_be_paid_target_cur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_paid_target_cur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('doc_paid_no', sa.String(length=255), nullable=True),
    sa.Column('doc_paid_date', sa.Date(), nullable=True),
    sa.Column('payment_proof_no', sa.String(length=255), nullable=True),
    sa.Column('payment_proof_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders_pobo.order_id'], ),
    sa.PrimaryKeyConstraint('term_id')
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders_pobo.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_bank_order_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('other_statement_id', sa.String(length=255), nullable=True),
    sa.Column('order_id_manual', sa.String(length=255), nullable=True),
    sa.Column('description_manual', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['other_statement_id'], ['other_bank_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overlapping',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_cobo_id', sa.String(length=255), nullable=True),
    sa.Column('amount_cobo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_cobo', sa.String(length=10), nullable=True),
    sa.Column('date_paid_cobo', sa.Date(), nullable=True),
    sa.Column('exchange_rate_cobo', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('amount_overlapped_cobo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exchange_rate_cobo_cur_to_pobo_cur_cobo_date', sa.Numeric(precision=18, scale=12), nullable=True),
    sa.Column('amount_target_currency_overlapped', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exchange_rate_cobo_cur_to_pobo_cur_pobo_date', sa.Numeric(precision=18, scale=12), nullable=True),
    sa.Column('amount_resting_cobo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('order_pobo_id', sa.String(length=255), nullable=True),
    sa.Column('amount_to_be_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_pobo', sa.String(length=10), nullable=True),
    sa.Column('date_paid_pobo', sa.Date(), nullable=True),
    sa.Column('exchange_rate_pobo', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('amount_overlapped_pobo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exchange_rate_differences', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_resting_pobo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profit_migrated_cobo_cur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profit_migrated_balance_cur', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_cobo'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['order_cobo_id'], ['orders_cobo.order_id'], ),
    sa.ForeignKeyConstraint(['order_pobo_id'], ['orders_pobo.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overlapping')
    op.drop_table('other_bank_order_overrides')
    op.drop_table('order_status_history')
    op.drop_table('order_pobo_terms')
    op.drop_index('idx_order_docs_type', table_name='order_documents')
    op.drop_table('order_documents')
    op.drop_table('order_cobo_terms')
    op.drop_table('mandiri_order_overrides')
    op.drop_table('instruction_export_items')
    op.drop_table('executed_orders')
    op.drop_table('other_bank_statements')
    op.drop_table('orders_pobo')
    op.drop_table('orders_cobo')
    op.drop_table('mandiri_statement')
    op.drop_table('mandiri_fx_fifo')
    op.drop_table('thresholds')
    op.drop_table('refunds')
    op.drop_table('payeer_accounts')
    op.drop_index('idx_orgdir_country', table_name='org_directory')
    op.drop_index('idx_orgdir_bic', table_name='org_directory')
    op.drop_table('org_directory')
    op.drop_table('membercheck_reports')
    op.drop_table('clients')
    op.drop_table('users')
    op.drop_table('sales_leads')
    op.drop_index('idx_payment_order_status', table_name='payment_order')
    op.drop_index('idx_payment_order_client', table_name='payment_order')
    op.drop_index('idx_payment_order_bic', table_name='payment_order')
    op.drop_table('payment_order')
    op.drop_table('kyc_search_history')
    op.drop_table('kyc_individuals')
    op.drop_table('kyc_companies')
    op.drop_table('instruction_exports')
    op.drop_table('faq_items')
    op.drop_table('exchange_rates')
    op.drop_table('entries')
    op.drop_table('currencies')
    op.drop_table('countries')
    op.drop_table('counterparties')
    op.drop_table('content_blocks')
    op.drop_table('bic_directory')
    op.drop_table('balance_reconcile')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
