"""add match_details to aml_alert

Revision ID: e3786b3bed0f
Revises: 34ed5d9c6ded
Create Date: 2026-03-27 19:58:18.886913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3786b3bed0f'
down_revision: Union[str, None] = '34ed5d9c6ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aml_alerts', sa.Column('match_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aml_alerts', 'match_details')
    # ### end Alembic commands ###
