"""leads: add converted_client_id and updated_at

Revision ID: e86bebb7b63f
Revises: 6c27839a655f
Create Date: 2026-05-14 19:53:47.237310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86bebb7b63f'
down_revision: Union[str, None] = '6c27839a655f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('converted_client_id', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_lead_converted_client', 'leads', ['converted_client_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'clients', ['converted_client_id'], ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index('idx_lead_converted_client', table_name='leads')
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'converted_client_id')
    # ### end Alembic commands ###
