"""add_client_id_to_aml_customers

Revision ID: eb922fbb5c78
Revises: 886b81748195
Create Date: 2026-03-20 18:54:03.446385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb922fbb5c78'
down_revision: Union[str, None] = '886b81748195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aml_customers', sa.Column('client_id', sa.String(length=255), nullable=True))
    op.create_index('idx_aml_customer_client_id', 'aml_customers', ['client_id'], unique=False)
    op.create_foreign_key(None, 'aml_customers', 'clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aml_customers', type_='foreignkey')
    op.drop_index('idx_aml_customer_client_id', table_name='aml_customers')
    op.drop_column('aml_customers', 'client_id')
    # ### end Alembic commands ###
