"""add report_s3_key and report_generated_at to aml_screenings

Revision ID: f65af2533a0e
Revises: 22f31128fd28
Create Date: 2026-04-20 15:52:40.429882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65af2533a0e'
down_revision: Union[str, None] = '22f31128fd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aml_screenings', sa.Column('report_s3_key', sa.String(length=512), nullable=True))
    op.add_column('aml_screenings', sa.Column('report_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aml_screenings', 'report_generated_at')
    op.drop_column('aml_screenings', 'report_s3_key')
    # ### end Alembic commands ###
