"""add performance indexes

Revision ID: f73916971801
Revises: ac190bf52f81
Create Date: 2026-03-09 21:37:59.336658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73916971801'
down_revision: Union[str, None] = 'ac190bf52f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_audit_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_index('idx_fx_fifo_account', 'mandiri_fx_fifo', ['account_no'], unique=False)
    op.create_index('idx_fx_fifo_order', 'mandiri_fx_fifo', ['order_id'], unique=False)
    op.create_index('idx_mandiri_account', 'mandiri_statement', ['account_no'], unique=False)
    op.create_index('idx_mandiri_client', 'mandiri_statement', ['client_id'], unique=False)
    op.create_index('idx_mandiri_value_date', 'mandiri_statement', ['value_date'], unique=False)
    op.create_index('idx_order_pobo_term_client', 'order_pobo_terms', ['client_id'], unique=False)
    op.create_index('idx_status_history_changed_at', 'order_status_history', ['changed_at'], unique=False)
    op.create_index('idx_status_history_order', 'order_status_history', ['order_id'], unique=False)
    op.create_index('idx_order_cobo_client', 'orders_cobo', ['client_id'], unique=False)
    op.create_index('idx_order_cobo_status', 'orders_cobo', ['status'], unique=False)
    op.create_index('idx_order_pobo_status', 'orders_pobo', ['status'], unique=False)
    op.create_index('idx_other_bank_client', 'other_bank_statements', ['client_id'], unique=False)
    op.create_index('idx_refund_order', 'refunds', ['order_id'], unique=False)
    op.drop_index(op.f('idx_transaction_reports_transaction_id'), table_name='transaction_reports')
    op.create_index('idx_transaction_reports_transaction_id', 'transaction_reports', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_reports_transaction_id', table_name='transaction_reports')
    op.create_index(op.f('idx_transaction_reports_transaction_id'), 'transaction_reports', ['transaction_id'], unique=True)
    op.drop_index('idx_refund_order', table_name='refunds')
    op.drop_index('idx_other_bank_client', table_name='other_bank_statements')
    op.drop_index('idx_order_pobo_status', table_name='orders_pobo')
    op.drop_index('idx_order_cobo_status', table_name='orders_cobo')
    op.drop_index('idx_order_cobo_client', table_name='orders_cobo')
    op.drop_index('idx_status_history_order', table_name='order_status_history')
    op.drop_index('idx_status_history_changed_at', table_name='order_status_history')
    op.drop_index('idx_order_pobo_term_client', table_name='order_pobo_terms')
    op.drop_index('idx_mandiri_value_date', table_name='mandiri_statement')
    op.drop_index('idx_mandiri_client', table_name='mandiri_statement')
    op.drop_index('idx_mandiri_account', table_name='mandiri_statement')
    op.drop_index('idx_fx_fifo_order', table_name='mandiri_fx_fifo')
    op.drop_index('idx_fx_fifo_account', table_name='mandiri_fx_fifo')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_index('idx_audit_created_at', table_name='audit_log')
    # ### end Alembic commands ###
