"""empty message

Revision ID: fbf49e28d02d
Revises: 0445f6083bf9
Create Date: 2025-12-23 11:58:11.564512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf49e28d02d'
down_revision: Union[str, None] = '0445f6083bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_directory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('bic_swift_cd', sa.String(length=12), nullable=True),
    sa.Column('chips_uid', sa.String(length=20), nullable=True),
    sa.Column('nm', sa.String(length=255), nullable=True),
    sa.Column('org_national_cd', sa.String(length=50), nullable=True),
    sa.Column('branch_nm', sa.String(length=255), nullable=True),
    sa.Column('addr_1', sa.String(length=255), nullable=True),
    sa.Column('addr_2', sa.String(length=255), nullable=True),
    sa.Column('addr_3', sa.String(length=255), nullable=True),
    sa.Column('city_nm', sa.String(length=120), nullable=True),
    sa.Column('substate_nm', sa.String(length=120), nullable=True),
    sa.Column('state_nm', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('is_inactive', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ctry_cd', sa.CHAR(length=2), nullable=True),
    sa.Column('national_org_dir_cd', sa.String(length=50), nullable=True),
    sa.Column('inter_bank_connection_sts', sa.String(length=50), nullable=True),
    sa.Column('is_active_mars', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['ctry_cd'], ['countries.ctry_cd'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orgdir_bic', 'org_directory', ['bic_swift_cd'], unique=False)
    op.create_index('idx_orgdir_country', 'org_directory', ['ctry_cd'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orgdir_country', table_name='org_directory')
    op.drop_index('idx_orgdir_bic', table_name='org_directory')
    op.drop_table('org_directory')
    # ### end Alembic commands ###
